[[docs]]
  name = "Overview"
  weight = 10
  identifier = "overview"
  url = "/docs/overview/"

[[docs]]
  name = "Tutorial"
  weight = 20
  identifier = "tutorial"
  url = "/docs/tutorial/"

[[docs]]
  name = "How-to Guides"
  weight = 30
  identifier = "how-to"
  url = "/docs/how-to/"

[[docs]]
  name = "Reference"
  weight = 40
  identifier = "reference"
  url = "/docs/reference/"

[[docs]]
  name = "Contributing"
  weight = 50
  identifier = "contributing"
  url = "/docs/contributing/"

[[docs]]
  name = "Help"
  weight = 60
  identifier = "help"
  url = "/docs/help/"

# [[docs]]
#   name = "Lorem"
#   weight = 70
#   identifier = "lorem"
#   url = "/docs/lorem/"

[[main]]
  name = "Showcase"
  url = "/showcase/"
  weight = 10

[[main]]
  name = "Docs"
  url = "/docs/overview/introduction/"
  weight = 20

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 30

[[main]]
  name = "Community"
  url = "#"
  weight = 40
  identifier = "community"

[[main]]
  name = "GitHub repository"
  weight = 10
  url = "https://github.com/h-enk/doks"
  post = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-external-link"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path><polyline points="15 3 21 3 21 9"></polyline><line x1="10" y1="14" x2="21" y2="3"></line></svg>'
  parent = "community"
  [main.params]
    target = "_blank"

# [[main]]
#   name = "Contribute"
#   weight = 15
#   url = "/docs/contributing/how-to-contribute/"
#   parent = "community"

[[main]]
  name = "Discussions"
  weight = 20
  url = "https://github.com/h-enk/doks/discussions"
  post = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-external-link"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path><polyline points="15 3 21 3 21 9"></polyline><line x1="10" y1="14" x2="21" y2="3"></line></svg>'
  parent = "community"
  [main.params]
    target = "_blank"

[[main]]
  name = "Open Collective"
  weight = 30
  url = "https://opencollective.com/doks"
  post = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-external-link"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path><polyline points="15 3 21 3 21 9"></polyline><line x1="10" y1="14" x2="21" y2="3"></line></svg>'
  parent = "community"
  [main.params]
    target = "_blank"

[[main]]
  name = "Hyas website"
  weight = 40
  url = "https://gethyas.com/"
  post = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-external-link"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path><polyline points="15 3 21 3 21 9"></polyline><line x1="10" y1="14" x2="21" y2="3"></line></svg>'
  parent = "community"
  [main.params]
    target = "_blank"

# [[main]]
#   name = "Get Started"
#   weight = 30
#   identifier = "get-started"
#   url = "/docs/overview/introduction/"
#
# [[main]]
#   name = "Quick Start"
#   weight = 40
#   identifier = "quick-start"
#   url = "/docs/overview/quick-start/"
#   parent = "get-started"
#
# [[main]]
#   name = "Tutorial"
#   weight = 50
#   identifier = "tutorial"
#   url = "https://getdoks.org/docs/tutorial/introduction/"
#   parent = "get-started"

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/h-enk/doks"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/getdoks"
  weight = 20

[[footer]]
  name = "Privacy"
  url = "/privacy-policy/"
  weight = 20

# [[footer]]
#   name = "Code of Conduct"
#   url = "/docs/contributing/code-of-conduct/"
#   weight = 30

# [[footer]]
#   name = "Open Collective"
#   url = "https://opencollective.com/doks"
#   weight = 40

[[secondary]]
  name = "Get Support"
  url = "/docs/help/faq/#can-i-get-support"
  weight = 10

[[showcase]]
  name = "Browse"
  weight = 10
  identifier = "browse"
  url = "/showcase/"

[[tertiary]]
  name = "Submit to Showcase"
  url = "https://github.com/h-enk/doks/discussions?discussions_q=category%3A%22Show+and+tell%22"
  weight = 10
