contact_links:
  - name: ğŸ“„ Doks
    url: https://github.com/gethyas/doks/issues/new/choose
    about: File an issue or make an improvement to Doks.
  - name: ğŸ’ Support
    url: https://github.com/gethyas/doks/discussions
    about: 'Get help on Doks Discussions'
