contact_links:
    - name: ğŸ“„ Doks
      url: https://github.com/thuliteio/doks
      about: File an issue or make an improvement to Doks.
    - name: ğŸ’ Support
      url: https://github.com/thuliteio/doks/discussions
      about: 'Get help on Doks Discussions'
