# [[docs]]
#   name = "Prologue"
#   weight = 10
#   identifier = "prologue"
#   url = "/docs/prologue/"

# [[docs]]
#   name = "Help"
#   weight = 60
#   identifier = "help"
#   url = "/docs/help/"

# [[docs]]
#   name = "Lorem"
#   weight = 70
#   identifier = "lorem"
#   url = "/docs/lorem/"

[[guide]]
  name = "Lorem"
  weight = 10
  identifier = "lorem"
  url = "/guide/lorem/"

[[tutorial]]
  name = "Lorem"
  weight = 10
  identifier = "lorem"
  url = "/tutorial/lorem/"

[[main]]
  name = "Docs"
  url = "/docs/start-here/getting-started/"
# url = "/docs/1.0/start-here/getting-started/"
  weight = 10

[[main]]
  name = "Showcase"
  url = "/showcase/"
  weight = 20

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 30

[[main]]
  name = "Discussions"
  url = "https://github.com/gethyas/doks/discussions"
  post = '<svg xmlns="http://www.w3.org/2000/svg" class="ms-1 mb-1 icon icon-tabler icon-tabler-external-link" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 6h-6a2 2 0 0 0 -2 2v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-6" /><path d="M11 13l9 -9" /><path d="M15 4h5v5" /></svg>'
  weight = 40

[[main]]
  name = "Hyas"
  url = "https://gethyas.com"
  post = '<svg xmlns="http://www.w3.org/2000/svg" class="ms-1 mb-1 icon icon-tabler icon-tabler-external-link" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 6h-6a2 2 0 0 0 -2 2v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-6" /><path d="M11 13l9 -9" /><path d="M15 4h5v5" /></svg>'
  weight = 50

# [[main]]
#   name = "Other docs"
#   url = "https://github.com/gethyas/doks/discussions"
#   weight = 50
#   identifier = "other-docs"
#
# [[main]]
#   name = "Hyas"
#   weight = 51
#   url = "https://docs.gethyas.com/"
#   parent = "other-docs"
#
# [[main]]
#   name = "Images"
#   weight = 52
#   url = "https://images.gethyas.com/"
#   parent = "other-docs"

# [[main]]
#   name = "Inline SVG"
#   weight = 53
#   url = "https://svg.gethyas.com/"
#   parent = "other-docs"
#
# [[main]]
#   name = "SEO"
#   weight = 54
#   url = "https://seo.gethyas.com/"
#   parent = "other-docs"

[[social]]
  name = "GitHub"
  pre = '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-brand-github" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M9 19c-4.3 1.4 -4.3 -2.5 -6 -3m12 5v-3.5c0 -1 .1 -1.4 -.5 -2c2.8 -.3 5.5 -1.4 5.5 -6a4.6 4.6 0 0 0 -1.3 -3.2a4.2 4.2 0 0 0 -.1 -3.2s-1.1 -.3 -3.5 1.3a12.3 12.3 0 0 0 -6.2 0c-2.4 -1.6 -3.5 -1.3 -3.5 -1.3a4.2 4.2 0 0 0 -.1 3.2a4.6 4.6 0 0 0 -1.3 3.2c0 4.6 2.7 5.7 5.5 6c-.6 .6 -.6 1.2 -.5 2v3.5"></path></svg>'
  url = "https://github.com/gethyas/doks"
  post = "v1.3.0"
  weight = 10

[[social]]
  name = "Mastodon"
  pre = '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-brand-mastodon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M18.648 15.254c-1.816 1.763 -6.648 1.626 -6.648 1.626a18.262 18.262 0 0 1 -3.288 -.256c1.127 1.985 4.12 2.81 8.982 2.475c-1.945 2.013 -13.598 5.257 -13.668 -7.636l-.026 -1.154c0 -3.036 .023 -4.115 1.352 -5.633c1.671 -1.91 6.648 -1.666 6.648 -1.666s4.977 -.243 6.648 1.667c1.329 1.518 1.352 2.597 1.352 5.633s-.456 4.074 -1.352 4.944z"></path><path d="M12 11.204v-2.926c0 -1.258 -.895 -2.278 -2 -2.278s-2 1.02 -2 2.278v4.722m4 -4.722c0 -1.258 .895 -2.278 2 -2.278s2 1.02 2 2.278v4.722"></path></svg>'
  url = "https://fosstodon.org/@doks"
  weight = 20

[[social]]
  name = "Twitter"
  pre = '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-brand-x" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M4 4l11.733 16h4.267l-11.733 -16z"></path><path d="M4 20l6.768 -6.768m2.46 -2.46l6.772 -6.772"></path></svg>'
  url = "https://twitter.com/getdoks"
  weight = 30

[[sidebar_upgrade-guides]]
  name = "Upgrade to v1"
  pageRef = "/upgrade-guides/upgrade-to-v1/"
  weight = 10

[[footer]]
  name = "Privacy Policy"
  url = "https://gethyas.com/privacy/"
  weight = 10

[[footer]]
  name = "Terms of Service"
  url = "https://gethyas.com/terms/"
  weight = 20
